### ISSUE TITLE
insertUpdate method planned?

### ISSUE THREAD

**Issue by jfoliveira** [jdavidbakr/replaceable-model#1]
Hi,

Great package! Thanks for making it publicly available!
Using the existing `replace` method a `replace into ...` command will be executed. As that causes the delete triggers to run, it would be nice if an `insertUpdate` method was also available, performing a SQL query like below:

``` sql
"insert into table (`id`, ...) values (?, ...) 
on duplicate key update 
column1 = ?, 
column2 = ?, ...;
```

This way it would be possible to `"replace"` an existing record without deleting the existing one first.

**Comment by jdavidbakr** [comment]
What would make sense as to the arguments of the insertUpdate() call?  I've not used that personally, the insert ignore has always met my needs - but it looks like there would need to be an additional key/value set for the 'on duplicate key update'

**Comment by jfoliveira** [comment]
@jdavidbakr Yeah, you could expect additional array for the columns/values to be used when a row is duplicated or perhaps you can just assume everything but the primary key should be updated.

**Comment by jdavidbakr** [comment]
I think this is outside of the scope of what I want to do with this package, however I'll be happy to take a pull request for it.
