### ISSUE TITLE
Shouldn't transactions be used in place of "replace into"?

### ISSUE THREAD

**Issue by Patryk27** [jdavidbakr/replaceable-model#11]
Hi,

As in the title - shouldn't one use transactions over `replace into`?

1. `replace into` is a `delete + insert` under the hood, so if one has an `on delete cascade` relationship, doing `replace into` will force it to be executed.

2. `replace into` doesn't actually solve any atomicity issues, contrary to actual transactions.

**Comment by jdavidbakr** [comment]
If your project works better with transactions by all means use them.  There might be situations where deadlocks arise without nesting each query in a transaction which muddies up the code.
