### ISSUE TITLE
insertIgnore method doesn't use table prefix

### ISSUE THREAD

**Issue by kirill001** [jdavidbakr/replaceable-model#4]
I tried to use insertIgnore
`Post::insertIgnore($posts)`
And got the following error: 
`Base table or view not found: 1146 Table 'master.posts'  doesn't exist`  
I have a prefix in config/database.php.
- Laravel version: 5.2

**Comment by timothepearce** [comment]
@kirill001 your error isn't related to this package. Your log seems to belongs to a bad migration or table declaration. Look at Laravel documentation and check that a simple call to your model works : 
`php artisan tinker` and then `App\Post::all()`
