### ISSUE TITLE
The executeQuery method is not returning anything

### ISSUE THREAD

**Issue by simbeto** [jdavidbakr/replaceable-model#7]
The **insertIgnore** and **replace** is returning the result of **executeQuery** mehtod BUT the executeQuery method is not returning anything...

What would be the result when the query succeed or failed? Boolean true/false or something else?

**Comment by jdavidbakr** [comment]
I believe if it fails it will throw an exception.

**Comment by simbeto** [comment]
What about when its successful? 
How do we know if the query succeed and based on that i have to do further tasks...
Am actually firing another query ONLY if the first one is successful.

This is how i modified the code and returning the return value:
// Return the result of the executed query 

```
protected static function executeQuery($command, array $attributes) {
        ...

	$result = \DB::connection($model->getConnectionName())->insert($query, $bindings);

	if ($result == TRUE)
		$model->fireModelEvent('saved', FALSE);

	return $result;
}
```
