### ISSUE TITLE
Using this trait outside of Laravel

### ISSUE THREAD

**Issue by emilorol** [jdavidbakr/replaceable-model#8]
Hi,

Thank you for putting together this solution as it is like a life saver.

I using Eloquent with Slim and I used composer to install this library.

I added it to my model:

```php
use Illuminate\Database\Eloquent\Model;
use \jdavidbakr\ReplaceableModel\ReplaceableModel;

class Cars extends Model
{
    use ReplaceableModel;
    protected $table = 'cars';
}
```

and I call my query:

```php
use App\Models\Cars;
class Car extends Controller
{
  public function save_them($data)
  {
     Cars::insertIgnore($data);
  }
}
```

But I get this error:

```
Type: Error
Message: Class 'DB' not found
File: /vendor/jdavidbakr/replaceable-model/src/ReplaceableModel.php
Line: 53
```

Any ideas?

**Note:** I have eloquent working using any other query method

**Comment by emilorol** [comment]
I found a solution that work in my case and I am posting it here in case someone is on the same boat.

I end up using this library instead:

https://github.com/yadakhov/insert-on-duplicate-key

It work like a charm and the setup is almost identical with even some more functionality.

Once again thank you for this library.

**Comment by jdavidbakr** [comment]
This library does require the DB facade which is a Laravel feature.

**Comment by emilorol** [comment]
I tried adding it without luck.

**Comment by jdavidbakr** [comment]
I'm not familiar with Slim, but in Laravel the DB class that you're missing is installed as an alias in the Laravel bootstrapping.  If you're getting that error, the environment is not configured as it would be in a Laravel project.
